import scrapy

class HeadingSpider(scrapy.Spider):
    name = "heading function"

    start_urls = [
        "https://timesofindia.indiatimes.com/city/amritsar/gurdaspur-man-dies-in-accident-in-saudi-firm/articleshow/63979282.cms?",
        "https://timesofindia.indiatimes.com/city/patna/three-accidents-claim-8-lives/articleshow/63977310.cms?",
        "https://timesofindia.indiatimes.com/city/rajkot/father-son-duo-die-in-accident/articleshow/63977663.cms?",
        "https://timesofindia.indiatimes.com/city/surat/road-accidents-claim-three-lives-in-city/articleshow/63978358.cms?",
        "https://timesofindia.indiatimes.com/city/shimla/6-pilgrims-from-punjab-die-in-una-accident/articleshow/63981002.cms?",
        "https://timesofindia.indiatimes.com/city/gurgaon/dhankar-announces-ex-gratia-for-dadri-accident-victims/articleshow/63992751.cms?",
        "https://timesofindia.indiatimes.com/city/chandigarh/haryana-sees-second-school-vehicle-accident-in-2-days/articleshow/64009558.cms?",
        "https://timesofindia.indiatimes.com/city/kolkata/three-teens-killed-in-two-bike-accidents/articleshow/64011901.cms?",
        "https://timesofindia.indiatimes.com/city/gurgaon/man-trapped-in-mangled-truck-for-an-hour-after-accident-on-nh-8-rescued/articleshow/64035880.cms?",
        "https://timesofindia.indiatimes.com/city/chandigarh/kin-of-accident-victim-get-rs-24-lakh/articleshow/64038974.cms?",
        "https://timesofindia.indiatimes.com/city/jaipur/five-dungarpur-pilgrims-hurt-in-ukhand-accident/articleshow/64046558.cms?",
        "https://timesofindia.indiatimes.com/city/pune/son-of-biker-who-died-in-accident-on-way-to-pune-will-sue-state-government/articleshow/64049493.cms?",
        "https://timesofindia.indiatimes.com/city/chandigarh/3-youths-assault-28-yr-old-woman-after-car-crash/articleshow/64056126.cms?",
        "https://timesofindia.indiatimes.com/city/pune/rs-1-5cr-as-damages-for-kin-of-school-headmaster-killed-in-accident/articleshow/64056187.cms?",
        "https://timesofindia.indiatimes.com/city/kochi/an-accident-waiting-to-happen-on-kochi-road/articleshow/64075674.cms?",
        "https://timesofindia.indiatimes.com/city/chandigarh/21-yr-old-killed-in-accident-on-his-way-back-from-manali/articleshow/64070342.cms?",
        "https://timesofindia.indiatimes.com/city/chandigarh/organs-from-21-year-old-killed-in-accident-save-3-lives/articleshow/64071484.cms?",
        "https://timesofindia.indiatimes.com/city/vadodara/biker-dies-another-loses-legs-in-accident/articleshow/64070416.cms?",
        "https://timesofindia.indiatimes.com/city/kolkata/early-morning-app-cab-crash-leaves-techie-critical/articleshow/64090740.cms?",
        "https://timesofindia.indiatimes.com/city/chandigarh/riding-without-helmets-duo-killed-in-motorcycle-crash/articleshow/64086345.cms?",
        "https://timesofindia.indiatimes.com/sports/off-the-field/shardul-thakurs-parents-injured-in-road-accident/articleshow/64092179.cms?",
        "https://timesofindia.indiatimes.com/city/trichy/2-accidents-at-musiri-leave-16-injured/articleshow/64086513.cms?",
        "https://timesofindia.indiatimes.com/city/kochi/seven-from-mundakkayam-killed-in-palani-road-accident/articleshow/64089945.cms?",
        "https://timesofindia.indiatimes.com/city/ludhiana/student-leader-dies-in-road-accident/articleshow/64090513.cms?",
        "https://timesofindia.indiatimes.com/city/gurgaon/when-will-papa-return-asks-son-of-cabbie-killed-in-sikanderpur-underpass-crash/articleshow/64101878.cms?",
        "https://timesofindia.indiatimes.com/city/kochi/7-pilgrims-from-kottayam-killed-in-accident-in-palani/articleshow/64103150.cms?",
        "https://timesofindia.indiatimes.com/city/kolkata/one-doctor-dies-in-accident-another-fights-for-life/articleshow/64103598.cms?",
        "https://timesofindia.indiatimes.com/city/jaipur/asi-among-two-killed-in-accident/articleshow/64115915.cms?",
        "https://timesofindia.indiatimes.com/city/jaipur/bank-officer-killed-in-baran-accident/articleshow/64115998.cms?",
        "https://timesofindia.indiatimes.com/city/chandigarh/rs-20l-relief-and-jobs-for-kin-of-power-plant-accident-victims/articleshow/64116276.cms?",
        "https://timesofindia.indiatimes.com/city/chennai/eight-of-a-family-among-nine-killed-in-tn-road-accident/articleshow/64118595.cms?",
        "https://timesofindia.indiatimes.com/city/kochi/high-court-relief-for-accident-victims-mother/articleshow/64119343.cms?",
        # "https://timesofindia.indiatimes.com/entertainment/hindi/bollywood/photo-features/jacqueline-fernandez-meets-with-a-car-accident-post-race-3-party/photostory/64119758.cms",
        "https://timesofindia.indiatimes.com/city/kochi/koruthodu-bids-adieu-to-7-killed-in-accident/articleshow/64119895.cms?",
        "https://timesofindia.indiatimes.com/city/indore/accident-vehicle-carrying-15-workers-crashes-14-injured/articleshow/64129911.cms?",
        "https://timesofindia.indiatimes.com/city/kolkata/racing-buses-crash-12-injured/articleshow/64132481.cms?",
        "https://timesofindia.indiatimes.com/city/kolkata/seven-killed-in-bengal-accident/articleshow/64134752.cms?",
        "https://timesofindia.indiatimes.com/city/coimbatore/four-men-killed-in-two-separate-road-accidents-in-district-in-two-days/articleshow/64142058.cms?",
        "https://timesofindia.indiatimes.com/city/ahmedabad/gulbai-tekra-accident-girl-killed/articleshow/64141751.cms?",
        "https://timesofindia.indiatimes.com/city/chandigarh/civil-hospital-doctor-another-staffer-killed-in-accident-one-injured/articleshow/64142148.cms?",
        "https://timesofindia.indiatimes.com/city/shimla/himachal-pradesh-6-killed-in-shimla-car-accident/articleshow/64145505.cms?",
        "https://timesofindia.indiatimes.com/city/mumbai/businessmans-son-friend-die-in-accident-on-lalbaug-flyover/articleshow/64151897.cms?",
        "https://timesofindia.indiatimes.com/city/patna/3-rjd-netas-among-four-die-in-accident/articleshow/64151215.cms?",
        "https://timesofindia.indiatimes.com/city/shimla/14-killed-in-2-hp-road-accidents/articleshow/64152282.cms?",
        "https://timesofindia.indiatimes.com/city/madurai/drunk-driver-kills-motorist-in-accident/articleshow/64151808.cms?",
        "https://timesofindia.indiatimes.com/city/madurai/six-pilgrims-killed-in-road-accident-near-sattur/articleshow/64151810.cms?",
        "https://timesofindia.indiatimes.com/city/trichy/five-of-a-family-die-three-injured-in-road-accident/articleshow/64152128.cms?",
        "https://timesofindia.indiatimes.com/city/coimbatore/four-killed-in-two-road-accidents/articleshow/64152184.cms?",
        "https://timesofindia.indiatimes.com/city/puducherry/three-killed-in-accident-in-puducherry/articleshow/64152318.cms?",
        "https://timesofindia.indiatimes.com/city/pune/biker-with-pillion-rider-crashes-into-youths-bike-duo-assault-him-with-aides/articleshow/64165904.cms?",
        "https://timesofindia.indiatimes.com/city/surat/woman-three-youths-die-in-two-accidents/articleshow/64181593.cms?",
        "https://timesofindia.indiatimes.com/city/rajkot/businessman-dies-in-accident/articleshow/64182306.cms?",
        "https://timesofindia.indiatimes.com/city/vadodara/two-killed-in-accidents-on-nh-8/articleshow/64181938.cms?",
        "https://timesofindia.indiatimes.com/city/pune/sunk-concrete-covers-in-ramwadi-underpass-cause-accidents/articleshow/64196926.cms?",
        "https://timesofindia.indiatimes.com/city/rajkot/two-accidents-claim-four-lives-in-sayla-bhuj/articleshow/64195174.cms?",
        "https://timesofindia.indiatimes.com/city/vadodara/three-of-family-killed-in-road-accident/articleshow/64196924.cms?",
        "https://timesofindia.indiatimes.com/city/chennai/after-deadly-accidents-malls-get-2-week-licence-deadline/articleshow/64212339.cms?",
        "https://timesofindia.indiatimes.com//city/jammu/guntur-soldier-dies-in-jk-accident/articleshow/64217241.cms",
        "https://timesofindia.indiatimes.com/city/trichy/two-killed-in-separate-accidents/articleshow/64212586.cms?",
        "https://timesofindia.indiatimes.com/city/ahmedabad/nurse-dies-after-road-accident/articleshow/64212801.cms?",
        "https://timesofindia.indiatimes.com/city/pune/5-from-nigdi-killed-in-accident-at-bhigwan/articleshow/64228210.cms?",
        "https://timesofindia.indiatimes.com/city/coimbatore/man-dies-in-accident/articleshow/64228620.cms?",
        "https://timesofindia.indiatimes.com/city/gurgaon/another-accident-at-underpass-in-gurgaon-cabbie-fell-asleep-at-wheel/articleshow/64228524.cms?",
        "https://timesofindia.indiatimes.com/city/shimla/nurpur-bus-accident-victims-parents-give-govt-5-day-ultimatum-to-act-against-erring-depts/articleshow/64228627.cms?",
        "https://timesofindia.indiatimes.com/city/shimla/himachal-11-rajasthan-tourists-injured-in-bus-accident-in-bilaspur-district/articleshow/64233872.cms?",
        "https://timesofindia.indiatimes.com/city/hyderabad/journey-to-anantagiri-hills-turns-fatal-4-die-in-car-crash/articleshow/64230112.cms?",
        "https://timesofindia.indiatimes.com/city/trichy/three-killed-in-road-accident/articleshow/64240186.cms?",
        "https://timesofindia.indiatimes.com/city/trichy/3-teen-boys-killed-in-road-accident/articleshow/64240192.cms?",
        "https://timesofindia.indiatimes.com/city/madurai/three-of-a-family-killed-in-accident/articleshow/64240371.cms?",
        "https://timesofindia.indiatimes.com/city/mumbai/accident-on-mumbai-ahmedabad-highway-leaves-one-dead/articleshow/64242936.cms?",
        "https://timesofindia.indiatimes.com/city/madurai/seven-killed-in-two-road-accidents/articleshow/64250101.cms",
        "https://timesofindia.indiatimes.com/city/rajkot/three-killed-in-two-separate-accidents/articleshow/64249348.cms",
        "https://timesofindia.indiatimes.com/city/hyderabad/accident-at-bridge-contractor-booked/articleshow/64252821.cms",
        "https://timesofindia.indiatimes.com/entertainment/bhojpuri/movies/news/bhojpuri-film-actress-manisha-rai-passes-away-in-road-accident/articleshow/64253475.cms",
        "https://timesofindia.indiatimes.com/city/bhopal/madhya-pradesh-9-killed-20-injured-in-bus-accident-at-guna/articleshow/64253543.cms",
        "https://timesofindia.indiatimes.com/city/patna/four-killed-in-darbhanga-bus-accident/articleshow/64249539.cms",
        "https://timesofindia.indiatimes.com/city/trichy/boy-dies-in-road-accident-22-injured/articleshow/64263851.cms",
        "https://timesofindia.indiatimes.com/city/erode/cop-misses-speed-breaker-dies-in-accident/articleshow/64263876.cms",
        "https://timesofindia.indiatimes.com/city/allahabad/locals-block-road-after-man-son-killed-in-accident/articleshow/64282839.cms",
        "https://timesofindia.indiatimes.com/city/coimbatore/parents-of-accident-victim-commit-suicide-in-avinashi/articleshow/64279525.cms",
        "https://timesofindia.indiatimes.com/city/coimbatore/parents-of-accident-victim-commit-suicide-in-avinashi/articleshow/64279525.cms",
        "https://timesofindia.indiatimes.com/tv/news/kannada/television-host-chandan-dies-in-road-accident/articleshow/64299825.cms",
        "https://timesofindia.indiatimes.com/city/vadodara/truck-crashes-into-house-in-chhota-udepur-kills-three/articleshow/64325349.cms",
        "https://timesofindia.indiatimes.com/city/chandigarh/23-year-old-killed-as-stray-causes-car-crash-on-flyover/articleshow/64326281.cms",
        "https://timesofindia.indiatimes.com/city/coimbatore/two-killed-in-separate-accidents/articleshow/64325642.cms",
        "https://timesofindia.indiatimes.com/city/goa/man-killed-in-self-accident/articleshow/64336988.cms",
        "https://timesofindia.indiatimes.com/city/pune/accident-on-expressway-triggers-one-hour-long-traffic-congestion/articleshow/64338874.cms",
        "https://timesofindia.indiatimes.com/india/19-crpf-personnel-injured-in-accident/articleshow/64339457.cms",
        "https://timesofindia.indiatimes.com/city/bhopal/engineering-student-2-others-die-in-accidents/articleshow/64339811.cms",
        "https://timesofindia.indiatimes.com/city/coimbatore/4-from-bluru-killed-27-injured-in-bus-accident/articleshow/64346416.cms",
        "https://timesofindia.indiatimes.com/city/surat/accidents-claim-four-lives-in-hazira-bhatar/articleshow/64345603.cms",
        "https://timesofindia.indiatimes.com/city/vadodara/nilgai-rushes-on-road-woman-dies-in-accident/articleshow/64346412.cms",
        "https://timesofindia.indiatimes.com/city/vadodara/seven-of-family-die-in-accident-near-adas/articleshow/64346440.cms",
        "https://timesofindia.indiatimes.com/city/hyderabad/rajiv-rahadari-accident-toll-goes-up-to-13/articleshow/64347076.cms",
        "https://timesofindia.indiatimes.com/city/bengaluru/karnataka-congress-mla-dies-in-road-accident/articleshow/64348998.cms",
        "https://timesofindia.indiatimes.com/city/bhopal/biker-skids-after-sneezing-crashes-into-a-pole-dies/articleshow/64363195.cms",
        "https://timesofindia.indiatimes.com/city/chandigarh/8-pilgrims-from-punjab-hurt-after-car-crashes-into-mountain/articleshow/64360866.cms",
        "https://timesofindia.indiatimes.com/city/trichy/two-killed-in-accidents-near-sirkazhi/articleshow/64360638.cms",
        "https://timesofindia.indiatimes.com/city/coimbatore/3-men-die-in-seperate-accidents/articleshow/64360811.cms",
        "https://timesofindia.indiatimes.com/city/trichy/girl-who-died-in-accident-is-the-deity-of-this-temple/articleshow/64375796.cms",
        "https://timesofindia.indiatimes.com/city/coimbatore/woman-son-killed-in-road-accident/articleshow/64375810.cms",
        "https://timesofindia.indiatimes.com/city/delhi/police-plan-to-reconstruct-harley-accident-on-dnd/articleshow/64376044.cms",
        "https://timesofindia.indiatimes.com/city/vadodara/accident-sparks-mob-fury-in-fajalpur/articleshow/64375670.cms",
        "https://timesofindia.indiatimes.com/city/chandigarh/68-year-old-killed-another-injured-as-city-witnesses-two-accidents/articleshow/64379935.cms"
    ]

    def parse(self, response):
            title = response.xpath('//div[@class="main-content"]/section/h1/arttitle/text()').extract_first()
            # title = response.xpath('//td[@align="left"]/span/a/text()').extract()
            # location = response.xpath('//div[@id="artLocation"]/div/text()').extract_first()
            # source = response.xpath('//div[@id="artSource"]/div/text()').extract_first()
            # top_line = response.xpath('//div[@id="divArticleContent"]/text()').extract_first()
            # lines = response.xpath('//div[@id="divArticleContent"]/p/text()').extract()
        
            yield {
            'title' : title
            }

            # yield {
            # 'title' : title,
            # 'location' : location,
            # 'source' : source,
            # 'top-line':  top_line,
            # 'lines':  lines,
        # }

    # def parse(self, response):
    #         yield {
    #         'title' : response.xpath('//div[@id="divTitle"]/text()').extract_first(),
    #         'location' : response.xpath('//div[@id="artLocation"]/div/text()').extract_first(),
    #         'source' : response.xpath('//div[@id="artSource"]/div/text()').extract_first(),
    #         'top-line':  response.xpath('//div[@id="divArticleContent"]/text()').extract_first(),
    #         'lines':  response.xpath('//div[@id="divArticleContent"]/p/text()').extract(),
    #     }